name: Build & Test Main

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    name: Build and Test the Marketplace Interface
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "17"
          cache: "npm"
      - run: npm ci
      - run: 
      - run: npm run prettier
      - run: npm run lint
      - run: npm run build
      - run: npm run test
